minor/urls.py
from django.contrib import admin
from django.urls import path,include
from .import views
from django.views.generic import ListView,CreateView,DetailView,UpdateView,DeleteView
from .views import home
app_name='minor'

urlpatterns = [path('',view=views.home,name='home'),
path('teacher',view=views.teacher,name='teacher'),
path('<id>/',view=views.upv,name='upvote'),
path('admin/', admin.site.urls,name='admin'),
#path('/student',view=views.student,name='home'),
               ]

untitled9/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('minor.urls',namespace='minor'))]

minor/models.py
from django.db import models

# Create your models here.
from django.db import models

# Create your models here.
class Logg(models.Model):
    name=models.CharField(max_length=50, default='')
    department=models.CharField(max_length=40,default='')
    authid=models.CharField(max_length=50,default='')
    question=models.CharField(max_length=200,default='')
    answer = models.CharField(max_length=200, default='')
    confirm=models.CharField(max_length=5,default=False,help_text="yes/no")
    upvote=models.IntegerField(default=0)

minor/forms.py
from .models import Logg
from django import forms
class Myforms(forms.ModelForm):

    class Meta:
        model=Logg
        fields=('name','department','authid','question')
        #fields="__all__"
        #exclude=['title']

minor/views.py
from django.shortcuts import render,redirect
from .forms import Myforms
from .models import Logg
from django.db.models import F

# Create your views here.
def home(request):
    dataa=Logg.objects.filter(confirm="yes")
    return render(request,'minor/homee.html',{'dataa':dataa})
def teacher(request):
    form = Myforms()
    if request.method == 'POST':
        form = Myforms(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/')
        else:
            form = Myforms()

    return render(request, 'minor/myformt.html', {'form': form})


def upv(request,id):
    reporter = Logg.objects.get(id=id)
    reporter.upvote = reporter.upvote+1
    reporter.save()
    return redirect('/')

templates/minor/homee.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Base</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
</head>
  <body>
    <nav class="navbar navbar-default navbar-static-top" >
      <div class="container" >
        <ul class="nav navbar-nav">
{# Django Home Link / Admin Link / Register Link#}
          <li><a class="navbar-brand" href="http://127.0.0.1:8000/admin">TEACHER</a></li>
          <li><a class="navbar-brand" href="{% url 'minor:teacher' %}">STUDENT</a></li>


</ul>
      </div>
    </nav>
    <div class="container">
        <h1>ANSWERED QUESTIONS</h1>
    </div>
  <div class="container">
<table class="table table-bordered">
   <tr>

       <th>question</th>


       <th>answer</th>
       <th>upvotes</th>

   </tr>
<tr>

    {% for x in dataa %}


          <td>{{ x.question }}</td>


    <td>{{ x.answer }}</td>
        <td>{{ x.upvote }}</td>
        <td> <a href="{% url 'minor:upvote' x.id  %}">
            <button type="button" class="likes" style="text-align:center;border-radius:40px;width: 100px;height: 40px">upvote</button>
            </a></td>

</tr>

    {% endfor %}

</table>




  </div>



  </body>
</html>

templates/minor/myformt.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <meta charset="UTF-8">
    <title>Title</title>
</head>

<body class="" bg-primary>

<form method="post">
{% csrf_token %}

<div class="form-group">

{{ form.as_table }}
</div>


<input class="btn btn-primary" type="submit" value="SUBMIT"/>

</form>
</body>

</html>